const { fontFamily } = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.tsx',
    './components/**/*.tsx',
    './node_modules/@tremor/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          900: '#000212',
        },
        tremor: {
          brand: {
            faint: '#eff6ff',
            muted: '#bfdbfe',
            subtle: '#60a5fa',
            DEFAULT: '#3b82f6',
            emphasis: '#1d4ed8',
            inverted: '#ffffff',
          },
          background: {
            muted: '#f9fafb',
            subtle: '#f3f4f6',
            DEFAULT: '#ffffff',
            emphasis: '#374151',
          },
          border: '#e5e7eb',
          ring: '#e5e7eb',
          content: {
            subtle: '#9ca3af',
            DEFAULT: '#6b7280',
            emphasis: '#374151',
            strong: '#111827',
            inverted: '#ffffff',
          },
        },
        'dark-tremor': {
          brand: {
            faint: '#0B1229',
            muted: '#172554',
            subtle: '#1e40af',
            DEFAULT: '#3b82f6',
            emphasis: '#60a5fa',
            inverted: '#030712',
          },
          background: {
            muted: '#131A2B',
            subtle: '#1f2937',
            DEFAULT: '#111827',
            emphasis: '#d1d5db',
          },
          border: '#1f2937',
          ring: '#1f2937',
          content: {
            subtle: '#4b5563',
            DEFAULT: '#6b7280',
          },
        },
      },
      fontSize: {
        xs: ['0.8125rem', { lineHeight: '1.5rem' }],
        sm: ['0.875rem', { lineHeight: '1.5rem' }],
        base: ['1rem', { lineHeight: '1.75rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '2rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '3.5rem' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.zinc.600'),
            '--tw-prose-headings': theme('colors.zinc.900'),
            '--tw-prose-links': theme('colors.teal.500'),
            '--tw-prose-links-hover': theme('colors.teal.600'),
            '--tw-prose-underline': theme('colors.teal.500 / 0.2'),
            '--tw-prose-underline-hover': theme('colors.teal.500'),
            '--tw-prose-bold': theme('colors.zinc.900'),
            '--tw-prose-counters': theme('colors.zinc.900'),
            '--tw-prose-bullets': theme('colors.zinc.900'),
            '--tw-prose-hr': theme('colors.zinc.100'),
            '--tw-prose-quote-borders': theme('colors.yellow.300'),
            '--tw-prose-captions': theme('colors.zinc.400'),
            '--tw-prose-code': theme('colors.zinc.700'),
            '--tw-prose-code-bg': theme('colors.zinc.300 / 0.2'),
            '--tw-prose-pre-code': theme('colors.zinc.100'),
            '--tw-prose-pre-bg': theme('colors.zinc.900'),
            '--tw-prose-pre-border': theme('colors.zinc.200'),
            '--tw-prose-th-borders': theme('colors.zinc.200'),
            '--tw-prose-td-borders': theme('colors.zinc.100'),
            '--tw-prose-invert-body': theme('colors.zinc.400'),
            '--tw-prose-invert-headings': theme('colors.zinc.200'),
            '--tw-prose-invert-links': theme('colors.teal.400'),
            '--tw-prose-invert-links-hover': theme('colors.teal.400'),
            '--tw-prose-invert-underline': theme('colors.teal.400 / 0.3'),
            '--tw-prose-invert-underline-hover': theme('colors.teal.400'),
            '--tw-prose-invert-bold': theme('colors.zinc.200'),
            '--tw-prose-invert-counters': theme('colors.zinc.200'),
            '--tw-prose-invert-bullets': theme('colors.zinc.200'),
            '--tw-prose-invert-hr': theme('colors.zinc.700 / 0.4'),
            '--tw-prose-invert-quote-borders': theme('colors.yellow.600'),
            '--tw-prose-invert-captions': theme('colors.zinc.500'),
            '--tw-prose-invert-code': theme('colors.zinc.300'),
            '--tw-prose-invert-code-bg': theme('colors.zinc.200 / 0.05'),
            '--tw-prose-invert-pre-code': theme('colors.zinc.100'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 0.4)',
            '--tw-prose-invert-pre-border': theme('colors.zinc.200 / 0.1'),
            '--tw-prose-invert-th-borders': theme('colors.zinc.700'),
            '--tw-prose-invert-td-borders': theme('colors.zinc.800'),
            color: 'var(--tw-prose-body)',
            lineHeight: theme('lineHeight.7'),
            '> *': {
              marginTop: theme('spacing.10'),
              marginBottom: theme('spacing.10'),
            },
            p: {
              marginTop: theme('spacing.7'),
              marginBottom: theme('spacing.7'),
            },
            'h2, h3': {
              color: 'var(--tw-prose-headings)',
              fontWeight: theme('fontWeight.semibold'),
            },
            h2: {
              fontSize: theme('fontSize.xl')[0],
              lineHeight: theme('lineHeight.7'),
              marginTop: theme('spacing.20'),
              marginBottom: theme('spacing.4'),
            },
            h3: {
              fontSize: theme('fontSize.base')[0],
              lineHeight: theme('lineHeight.7'),
              marginTop: theme('spacing.16'),
              marginBottom: theme('spacing.4'),
            },
            ':is(h2, h3) + *': {
              marginTop: 0,
            },
            a: {
              color: 'var(--tw-prose-links)',
              fontWeight: theme('fontWeight.semibold'),
              textDecoration: 'underline',
              textDecorationColor: 'var(--tw-prose-underline)',
              transitionProperty: 'color, text-decoration-color',
              transitionDuration: theme('transitionDuration.150'),
              transitionTimingFunction: theme('transitionTimingFunction.in-out'),
            },
            'a:hover': {
              color: 'var(--tw-prose-links-hover)',
              textDecorationColor: 'var(--tw-prose-underline-hover)',
            },
            strong: {
              color: 'var(--tw-prose-bold)',
              fontWeight: theme('fontWeight.semibold'),
            },
            code: {
              display: 'inline-block',
              color: 'var(--tw-prose-code)',
              fontSize: theme('fontSize.sm')[0],
              fontWeight: theme('fontWeight.semibold'),
              backgroundColor: 'var(--tw-prose-code-bg)',
              borderRadius: theme('borderRadius.lg'),
              paddingLeft: theme('spacing.1'),
              paddingRight: theme('spacing.1'),
            },
            'a code': {
              color: 'inherit',
            },
            ':is(h2, h3) code': {
              fontWeight: theme('fontWeight.bold'),
            },
            blockquote: {
              paddingLeft: theme('spacing.6'),
              borderLeftWidth: theme('borderWidth.2'),
              borderLeftColor: 'var(--tw-prose-quote-borders)',
              fontStyle: 'italic',
            },
            figcaption: {
              color: 'var(--tw-prose-captions)',
              fontSize: theme('fontSize.sm')[0],
              lineHeight: theme('lineHeight.6'),
              marginTop: theme('spacing.3'),
            },
            'figcaption > p': {
              margin: 0,
            },
            ul: {
              listStyleType: 'disc',
            },
            ol: {
              listStyleType: 'decimal',
            },
            'ul, ol': {
              paddingLeft: theme('spacing.6'),
            },
            li: {
              marginTop: theme('spacing.6'),
              marginBottom: theme('spacing.6'),
              paddingLeft: theme('spacing[3.5]'),
            },
            'li::marker': {
              fontSize: theme('fontSize.sm')[0],
              fontWeight: theme('fontWeight.semibold'),
            },
            'ol > li::marker': {
              color: 'var(--tw-prose-counters)',
            },
            'ul > li::marker': {
              color: 'var(--tw-prose-bullets)',
            },
            'li :is(ol, ul)': {
              marginTop: theme('spacing.4'),
              marginBottom: theme('spacing.4'),
            },
            'li :is(li, p)': {
              marginTop: theme('spacing.3'),
              marginBottom: theme('spacing.3'),
            },
            pre: {
              color: 'var(--tw-prose-pre-code)',
              backgroundColor: 'var(--tw-prose-pre-bg)',
              overflowX: 'auto',
              borderRadius: theme('borderRadius.xl'),
              border: '1px solid',
              borderColor: 'var(--tw-prose-pre-border)',
              padding: theme('spacing.8'),
              marginTop: theme('spacing.10'),
              marginBottom: theme('spacing.10'),
            },
            'pre code': {
              display: 'inline',
              color: 'inherit',
              fontSize: 'inherit',
              fontWeight: 'inherit',
              lineHeight: 'inherit',
              backgroundColor: 'transparent',
              borderRadius: 0,
              padding: 0,
            },
            table: {
              width: '100%',
              tableLayout: 'auto',
              textAlign: 'left',
              marginTop: theme('spacing.8'),
              marginBottom: theme('spacing.8'),
              fontSize: theme('fontSize.sm')[0],
              lineHeight: theme('lineHeight.6'),
            },
            thead: {
              borderBottomWidth: theme('borderWidth.2'),
              borderBottomColor: 'var(--tw-prose-th-borders)',
            },
            'thead th': {
              color: 'var(--tw-prose-headings)',
              fontWeight: theme('fontWeight.semibold'),
              verticalAlign: 'bottom',
              paddingRight: theme('spacing.2'),
              paddingBottom: theme('spacing.2'),
              paddingLeft: theme('spacing.2'),
            },
            'thead th:not(:first-child)': {
              paddingLeft: theme('spacing.2'),
            },
            'thead th:first-child': {
              paddingLeft: 0,
            },
            'thead th:last-child': {
              paddingRight: 0,
            },
            'tbody tr': {
              borderBottomWidth: '1px',
              borderBottomColor: 'var(--tw-prose-td-borders)',
            },
            'tbody tr:last-child': {
              borderBottomWidth: 0,
            },
            'tbody td': {
              verticalAlign: 'baseline',
              paddingRight: theme('spacing.2'),
              paddingTop: theme('spacing.2'),
              paddingBottom: theme('spacing.2'),
              paddingLeft: theme('spacing.2'),
            },
            'tbody td:not(:first-child)': {
              paddingLeft: theme('spacing.2'),
            },
            'tbody td:first-child': {
              paddingLeft: 0,
            },
            'tbody td:last-child': {
              paddingRight: 0,
            },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
}
